/* global process, console, URL */
// Shared bits for the three generators: header, normalisation, and the tiny CLI (--out <dir> | --check).
import { readFileSync, writeFileSync, mkdirSync, realpathSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

export const repoRoot = fileURLToPath(new URL("../../", import.meta.url));
export const specPath = join(repoRoot, "contracts/openapi.yaml");
export const HEADER = "// GENERATED by tools/contracts (source: contracts/openapi.yaml) — DO NOT EDIT\n";

// LF endings, no trailing whitespace, exactly one trailing newline: keeps output byte-stable across OSes.
export const normalize = (s) => s.replace(/\r\n/g, "\n").replace(/[ \t]+$/gm, "").replace(/\n*$/, "\n");

/** Run `build()` (returns file text) as a CLI. Default target is the committed location. */
export async function run(build, defaultRel) {
  const args = process.argv.slice(2);
  const outIdx = args.indexOf("--out");
  const text = normalize(await build());
  if (args.includes("--check")) {
    let cur = "";
    try {
      cur = readFileSync(join(repoRoot, defaultRel), "utf8");
    } catch {
      /* missing counts as drift */
    }
    if (cur !== text) {
      console.error(`DRIFT ${defaultRel}: committed output differs from a fresh generation (run make contracts)`);
      process.exit(1);
    }
    return;
  }
  const file = outIdx >= 0 ? join(args[outIdx + 1] ?? ".", defaultRel.split("/").pop()) : join(repoRoot, defaultRel);
  mkdirSync(dirname(file), { recursive: true });
  writeFileSync(file, text);
  console.log(`wrote ${outIdx >= 0 ? file : defaultRel}`);
}

// import.meta.main needs Node >= 24.2; CI runs 20
export const isMain = (url) => !!process.argv[1] && realpathSync(process.argv[1]) === realpathSync(fileURLToPath(url));
