/* global URL, process, fetch */
// AC3: generators. TS output is exercised by transpiling the COMMITTED files (Node 20 in CI cannot import .ts)
// into a tmp dir whose node_modules symlinks to the owning workspace, so `zod` / `msw` resolve normally.
import { test, before, after } from "node:test";
import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import { mkdtempSync, readFileSync, readdirSync, rmSync, symlinkSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { createRequire } from "node:module";
import { fileURLToPath, pathToFileURL } from "node:url";
import { parse } from "yaml";
import ts from "typescript";
import { buildTypes, TYPES_PATH } from "../gen-types.mjs";
import { buildZod, ZOD_PATH } from "../gen-zod.mjs";
import { buildMsw, MSW_PATH, readMap, specOperations, fixtureBody } from "../gen-msw.mjs";
import { normalize, repoRoot } from "../gen-util.mjs";

const HEADER = "// GENERATED by tools/contracts (source: contracts/openapi.yaml) — DO NOT EDIT\n";
const at = (p) => join(repoRoot, p);
const spec = parse(readFileSync(at("contracts/openapi.yaml"), "utf8"));
const { ops, unmapped } = readMap();
const tmps = [];
const tmp = () => {
  const d = mkdtempSync(join(tmpdir(), "vck-gen-test-"));
  tmps.push(d);
  return d;
};
after(() => tmps.forEach((d) => rmSync(d, { recursive: true, force: true })));

/** transpile a committed .ts file into a tmp dir that can resolve the workspace's node_modules */
async function importTs(rel, workspace, extra = {}) {
  const dir = tmp();
  symlinkSync(at(`${workspace}/node_modules`), join(dir, "node_modules"));
  const js = ts.transpileModule(readFileSync(at(rel), "utf8"), {
    compilerOptions: { module: ts.ModuleKind.ESNext, target: ts.ScriptTarget.ES2022 },
  }).outputText;
  writeFileSync(join(dir, "mod.mjs"), js);
  for (const [name, src] of Object.entries(extra)) writeFileSync(join(dir, name), src);
  return dir;
}

let zodMod, mswDir, mswMod;
before(async () => {
  const zd = await importTs(ZOD_PATH, "apps/backend");
  zodMod = await import(pathToFileURL(join(zd, "mod.mjs")).href);
  mswDir = await importTs(MSW_PATH, "apps/storefront", {
    "msw-runtime.mjs": 'export * from "msw"; export { setupServer } from "msw/node";',
  });
  mswMod = await import(pathToFileURL(join(mswDir, "mod.mjs")).href);
});

const pascal = (s) => s[0].toUpperCase() + s.slice(1);
const deref = (s) => (s?.$ref ? deref(s.$ref.split("/").slice(1).reduce((n, k) => n[k], spec)) : s);
const opById = (id) => specOperations().find((o) => o.id === id);
const responseSchema = (o, status) =>
  deref(deref(spec.paths[o.path][o.method].responses[status]).content["application/json"].schema);

test("[VCK-004-AC3] fixture-map: operationIds, files, statuses are real; every fixture is mapped or justified", () => {
  const files = readdirSync(at("contracts/fixtures")).filter((f) => f.endsWith(".json"));
  for (const [id, e] of Object.entries(ops)) {
    const o = opById(id);
    assert.ok(o, `unknown operationId ${id}`);
    assert.ok(files.includes(e.fixture), `missing fixture ${e.fixture}`);
    assert.ok(o.responses.includes(String(e.status)), `${id}: ${e.status} is not a documented response`);
    assert.notEqual(fixtureBody(e), undefined, `${id}: key ${e.key} not in ${e.fixture}`);
  }
  const used = new Set(Object.values(ops).map((e) => e.fixture));
  const listed = new Map(unmapped.map((u) => [u.file, u.reason]));
  for (const f of files) {
    assert.ok(used.has(f) || listed.get(f)?.trim(), `${f} is neither mapped nor listed with a reason in unmapped_fixtures`);
    assert.ok(!(used.has(f) && listed.has(f)), `${f} is both mapped and unmapped`);
  }
  for (const f of listed.keys()) assert.ok(files.includes(f), `unmapped_fixtures lists missing file ${f}`);
});

for (const ws of ["storefront", "backend"]) {
  test(`[VCK-004-AC3] generated output typechecks under apps/${ws} tsconfig`, () => {
    const tsc = createRequire(import.meta.url).resolve("typescript/bin/tsc");
    const r = spawnSync(process.execPath, [tsc, "-p", at(`apps/${ws}`), "--noEmit"], { encoding: "utf8" });
    assert.equal(r.status, 0, r.stdout + r.stderr);
  });
}

test("[VCK-004-AC3] every fixture-mapped response parses with its generated Zod validator; mutated ones fail", () => {
  for (const [id, e] of Object.entries(ops)) {
    const name = `${pascal(id)}Response`;
    const v = zodMod[name];
    assert.ok(v, `${name} not exported`);
    const body = fixtureBody(e);
    assert.equal(v.safeParse(body).success, true, `${id}: fixture rejected: ${JSON.stringify(v.safeParse(body).error?.issues)}`);
    const required = responseSchema(opById(id), e.status).required;
    assert.ok(required?.length, `${id}: expected required fields to mutate`);
    const field = required[0];
    const dropped = Object.fromEntries(Object.entries(body).filter(([k]) => k !== field));
    assert.equal(v.safeParse(dropped).success, false, `${id}: dropping ${field} should fail`);
    const wrong = { ...body, [field]: typeof body[field] === "object" && body[field] !== null && !Array.isArray(body[field]) ? 42 : { wrong: 1 } };
    assert.equal(v.safeParse(wrong).success, false, `${id}: wrong type for ${field} should fail`);
  }
});

test("[VCK-004-AC3] MSW handlers: one per mapped operation, spec path, fixture body and status", async (t) => {
  const { handlers } = mswMod;
  assert.equal(handlers.length, Object.keys(ops).length);
  const { setupServer } = await import(pathToFileURL(join(mswDir, "msw-runtime.mjs")).href);
  const server = setupServer(...handlers);
  server.listen({ onUnhandledRequest: "error" });
  t.after(() => server.close());
  for (const [id, e] of Object.entries(ops)) {
    const o = opById(id);
    const colon = "*" + o.path.replace(/\{([^}]+)\}/g, ":$1");
    assert.ok(
      handlers.some((h) => h.info.method.toLowerCase() === o.method && h.info.path === colon),
      `${id}: no ${o.method} ${colon} handler`,
    );
    const url = "http://localhost:9000" + o.path.replace(/\{[^}]+\}/g, "x_1");
    const res = await fetch(url, { method: o.method.toUpperCase() });
    assert.equal(res.status, e.status, id);
    assert.deepEqual(await res.json(), fixtureBody(e), id);
  }
});

const generators = [
  ["types", buildTypes, TYPES_PATH],
  ["zod", buildZod, ZOD_PATH],
  ["msw", buildMsw, MSW_PATH],
];
for (const [name, build, path] of generators) {
  test(`[VCK-004-AC3] gen-${name}: header, deterministic, LF, no absolute paths, no drift vs committed`, async () => {
    const a = normalize(await build());
    const b = normalize(await build());
    assert.equal(a, b, "two runs differ");
    assert.ok(a.startsWith(HEADER), "missing header");
    assert.ok(!a.includes("\r") && a.endsWith("\n") && !a.endsWith("\n\n"));
    assert.ok(!a.includes(repoRoot) && !a.includes(tmpdir()), "absolute path leaked");
    assert.equal(readFileSync(at(path), "utf8"), a, `${path} is stale: run make contracts`);
  });
}

test("[VCK-004-AC3] gen CLIs: --out writes byte-identical files, --check passes on committed output", () => {
  const out = tmp();
  for (const [name, , path] of generators) {
    const cli = fileURLToPath(new URL(`../gen-${name}.mjs`, import.meta.url));
    const w = spawnSync(process.execPath, [cli, "--out", out], { encoding: "utf8" });
    assert.equal(w.status, 0, w.stderr);
    assert.equal(readFileSync(join(out, path.split("/").pop()), "utf8"), readFileSync(at(path), "utf8"));
    const c = spawnSync(process.execPath, [cli, "--check"], { encoding: "utf8" });
    assert.equal(c.status, 0, c.stderr);
  }
});
